name: Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
        architecture: x64
        cache: 'pip'
    - run: pip install jsonschema
    - run: wget "http://json-schema.org/draft-04/schema" -O schemaschema
    - run: python -m jsonschema -V Draft4Validator -i schema/360-giving-schema.json -i schema/360-giving-package-schema.json schemaschema

